title: Research by Dr. Austin Brenner
remote_theme: jekyll/minima
collections:
    - posts
minima:
    nav_pages:
        - about.md
        - posts
    skin: solarized-dark
    show_excerpts: true
author: Austin Brenner aubr@umich.edu
description: Bookmark this to keep an eye on my project updates!
