domain: aubrspace.github.io
url: https://aubrspace.github.io
remote_theme: jekyll/minima
title: MGU2023 Dissecting Earth's Magnetosphere
author: Austin Brenner aubr@umich.edu
description: Bookmark this to keep an eye on my project updates!
