title: Research by Dr. Austin Brenner
remote_theme: jekyll/minima
minima:
    nav_pages:
        - about.md
        - _posts/AGU2023.md
        - _posts/GEM2025.md
    skin: solarized-dark
    show_excerpts: true
author: Austin Brenner aubr@umich.edu
description: Bookmark this to keep an eye on my project updates!
